---
title: "NumeriLab - Reproducibility and Collaborative coding"
author: "Arthur de Grandpré"
date: "20 mai 2019"
output:
  ioslides_presentation:
    css: styles.css
    logo: images/logo_rive_logo_txt_FR_ENG-01.png
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Context {.build}

Previous workshops have been:  

- Dedicated to enhancing coding and data science level

- Largely based on the R environment  

- Giving strong numeracy bases for everyone attending  
  
But...  
I feel like we still have yet to tackle some of basics of *coding hygiene* like:  

- How to ensure reproducibility of analysis  

- How to ensure safekeeping of your scripts  

- How to collaborate efficiently in your code oriented projects  

## Planning {.build}

The goal of this workshop is that by the end of the hour, attendees are able to figure out their own recipe for efficient collaborative coding.  
  
To do so, we will go through:  

- Basic annotation tips  

- How to structure scripts and projects efficiently  

- How to ensure safekeeping of scripts

- How to share your scripts and their results

## Important note

There is no single way of doing all that's gonna be shown today.  
  
The following material is based on my personnal experience and what has helped me when working with collaborators.  
  
This is mostly an effort to make sure everyone has some basic reflexes when working on their different scripts.  

## Reproducibility {.build}

While there are many ways to tackle reproducibility of an analysis, the easiest is probably to think your code for it since $T_0$.  
  
This can be done by: 

- Working by **projects**

- Not procrastinating on the use of # everywhere in your code (don't hesitate to overdescribe, or even interpret results)  

- Planning your code like you would plan a written document (flowing, logical process)  

- Using R Markdown (Thanks *Lucas*)  

- Structuring your code in the most generic way possible (the less specific you are, the easier it will be to transfer your code)

- Writing your own functions, or even packages  

## Exemples

(annotation exemples, structure exemples, specific vs general coding, using functions)

## Safekeeping

There are many different ways to backup your data and scripts.  
  
It can be done **locally**:  

- using redundancy on multiple devices (backups)  

- can be programmed weekly

- requires different hard drives in different places (some dedication)  

Or **remotely**:  

- Using cloud services (dropbox, google drive, onedrive, github)

- Usually very easy to use, but limited in terms of capacity

- Allows easy sharing